
IPM descriptor object - egg


```{r}

states <- c("egg", "not_an_egg")
states_z <- c("TRUE", "TRUE")
kernels <- c("Fec", "P")

par_info <- data.frame(t(data.frame(
   par1  =  c(par = "par1",min = -Inf,max = Inf,samp = T),
   par2  =  c(par = "par2",min = -Inf,max = Inf,samp = T)
)),stringsAsFactors=F)

par_info$min <- as.numeric(par_info$min);par_info$max <- as.numeric(par_info$max)

par_fns <- list(
#    par1  = function(params){0},
#    par2  = function(params){0}
)
```


```{r}
demo_fns <- list(
  demo_fn1= function(z1, z, params){
    #insert function here
    return()
  },
  demo_fn2= function(z1, z, params){
    #insert function here
    return()
  },
  demo_fn3= function(z1, z, params){
    #insert function here
    return()
  }
)
```

```{r}
kernel_fns <- init_nested_list(kernels,states)

### KERNEL: Fec
# egg -> egg
kernel_fns$Fec$egg$egg <- function (z1, z, params) {
   return()
}

# egg -> not_an_egg
kernel_fns$Fec$not_an_egg$egg <- function (z1, z, params) {
   return()
}

# not_an_egg -> egg
kernel_fns$Fec$egg$not_an_egg <- function (z1, z, params) {
   return()
}

# not_an_egg -> not_an_egg
kernel_fns$Fec$not_an_egg$not_an_egg <- function (z1, z, params) {
   return()
}


### KERNEL: P
# egg -> egg
kernel_fns$P$egg$egg <- function (z1, z, params) {
   return()
}

# egg -> not_an_egg
kernel_fns$P$not_an_egg$egg <- function (z1, z, params) {
   return()
}

# not_an_egg -> egg
kernel_fns$P$egg$not_an_egg <- function (z1, z, params) {
   return()
}

# not_an_egg -> not_an_egg
kernel_fns$P$not_an_egg$not_an_egg <- function (z1, z, params) {
   return()
}

```
Kernel size limit functions

```{r}
# lower size limit
limit_lower <- function(params,
egg
){
  
  return()
}

#upper size limit
limit_upper <- function(params,
egg
){
  
  return()
}

# function to determine the resolution of the kernel
kernel_res <- function(params,
egg
){
  
  return()
}
```

```{r}
egg<- list(
  states = states,
  states_z = states_z,
  kernels = kernels,
  par_info = par_info,
  par_fns = par_fns,
  demo_fns = demo_fns,
  kernel_fns = kernel_fns,
  limit_lower = limit_lower,
  limit_upper = limit_upper,
  kernel_res = kernel_res
)

class(egg) <- append(class(egg),'IPM_descriptor')
```
